/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103xx.h"
#include "stm32f1xx_gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delay(void)
{
    for (int t=0; t<500000; t++);
}


int main(void)
{
	GPIOx_PinConfig_t pinCfg = {0};
	pinCfg.GPIO_PinNum = PIN_13;
	pinCfg.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	pinCfg.GPIO_PinPull = GPIO_NOPULL;
	pinCfg.GPIO_PinSpeed = GPIO_SPEED_LOW;

	GPIOx_Handle_t handle = {.pGPIOx = GPIOC, .GPIO_pinConfig = pinCfg};

	GPIOx_ClkControl(handle.pGPIOx, ENABLE);
	GPIOx_Init(&handle);

    /* Loop forever */
	while(1)
	{
		GPIOx_PinToggle(GPIOC, PIN_13);
		delay();
	}
}
